---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: orders
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: thisisawesome12/orders:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: orders-env
        - secretRef:
            name: orders-secrets
      terminationGracePeriodSeconds: 180