---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: store
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: thisisawesome12/store:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: store-env
      terminationGracePeriodSeconds: 180