---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: payments
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: thisisawesome12/payments:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: payments-env
        - secretRef:
            name: payments-secrets
      terminationGracePeriodSeconds: 180