---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: products
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: thisisawesome12/products:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: products-env
        - secretRef:
            name: products-secrets
      terminationGracePeriodSeconds: 180